id: newrelic_logs_create_heroku_drain
hints:
startFlow:
  do:
  - actionId: bot_message
    params:
      person: head-of-rd
      messages:
      - text: Having a production application is nice but we have to have a way to know what’s going on, that’s why we added some logs to the system, but it looks like we don’t have an easy way to consume and search those.
        delay: 500
      - text: That’s why we decided to add NewRelic logs to our Heroku app.
        delay: 1000
      - text: Follow [New Relic’s documentation](https://docs.newrelic.com/docs/logs/forward-logs/heroku-log-forwarding/#create-syslog-drain) to configure a new Heroku syslog drain, by completing steps 1-3, and let me know once you’ve added a new drain
        delay: 1000
trigger:
  type: user_message_to_head-of-rd
  flowNode:
    do:
    - actionId: heroku_api_call
      name: heroku_log_drains
      params:
        path: /apps/${user.getBackendAppName()}/log-drains
    if:
      conditions:
        - conditionId: array_one
          name: heroku_log
          params:
            array: "[${outputs.heroku_log_drains.value}]"
            conditions:
              - conditionId: text_contains_strings
                params: 
                  text: ${item.url}
                  strings: 
                    - newrelic.syslog.nr-data.net
      then:
        do:
          - actionId: bot_message
            params:
              person: head-of-rd
              messages:
              - text: Great job. I see you’ve added a syslog drain to your application. I fetched the token for you, so you can configure it in New Relic - `${outputs.heroku_log.token}`
                delay: 1000
          - actionId: finish_step
      else:
        do:
          - actionId: bot_message
            params:
              person: head-of-rd
              messages:
              - text: Are you sure you’ve properly configured the drain? Something seems wrong
                delay: 0
