id: newrelic_logs_fix_error
learningObjectives: 
  - Fixing errors
hints:
  - Did you find where we call the unndefined function? Search for it in the code base, and try to figure out what's the correct call should be
startFlow:
  do:
  - actionId: bot_message
    params:
      person: head-of-rd
      messages:
      - text: Alright, now that we know where the error is, we can address it. Please open a pull request with a fix, and I’ll review it when I have some time
        delay: 1000
trigger:
  type: github_pr_lifecycle_status
  flowNode:
    switch:
      key: "${eventType}"
      cases:
        github_pr_opened:
          do:
          - actionId: bot_message
            params:
              person: head-of-rd
              messages:
              - text: Great job, let me go over the fix
                delay: 1000
          - actionId: github_pr_comment
            params:
              person: head-of-rd
              message: Great job, let me go over the fix
        github_pr_workflow_complete_success:
          if:
            conditions:
            - conditionId: github_is_file_modified
              paramsFramework:
                node:
                  fileName: backend/routes/api/tags.js
                rails:
                  fileName: backend/app/controllers/tags_controller.rb
                python:
                  fileName: backend/app/db/repositories/tags.py

            then:
              do:
              - actionId: bot_message
                params:
                  person: head-of-rd
                  messages:
                  - text: This looks good, you can go ahead and merge
                    delay: 1000
              - actionId: github_pr_approve
                params:
                  person: head-of-rd
                  message: This looks good, you can go ahead and merge

            else:
              do:
              - actionId: bot_message
                params:
                  person: head-of-rd
                  messages:
                  - text: I don’t think this will actually work, can you take a second look at your solution?
                    delay: 1000
              - actionId: github_pr_reject
                params:
                  person: head-of-rd
                  message: I don’t think this will actually work, can you take a second look at your solution?

        github_pr_merged:
          do:
          - actionId: finish_step


solution:
  do:
    - actionId: bot_message
        params:
          person: head-of-rd
        paramsFramework:
          node:
            messages:
              - text: "Let's fix the source of this issue! Go ahead to ` backend/routes/api/tags.js`. Find the call with a typo to the non existing function `distincts`, and fix it! "
                delay: 1000
              - text: "Once you're finished open a PR and I'll be there for you"
                delay: 1000
          rails:
            messages:
              - text: "Let's fix the source of this issue! Go ahead to `backend/app/controllers/tags_controller.rb`. Find the call with a typo  to the non existing function `most_use`, and fix it! "
                delay: 1000
              - text: "Once you're finished open a PR and I'll be there for you"
                delay: 1000
          python:
            messages:
              - text: "Let's fix the source of this issue! Go ahead to `backend/app/db/repositories/tags.py`. Find the call with a typo to the non existing function `get_all_tag`, and fix it! "
                delay: 1000
              - text: "Once you're finished open a PR and I'll be there for you"
                delay: 1000
