id: newrelic_logs_configure_heroku_logs
hints:
startFlow:
  do:
  - actionId: bot_message
    params:
      person: head-of-rd
      messages:
      - text: Go ahead and use the token to [register the new log drain in New Relic](https://docs.newrelic.com/docs/logs/forward-logs/heroku-log-forwarding/#register-syslog), and let me know when you’re done.
        delay: 1000
trigger:
  type: user_message_to_head-of-rd
  flowNode:
    if:
      conditions:
        - conditionId: is_user_message_text_ready_to_continue
      then:
        do:
          - actionId: bot_message
            params:
              person: head-of-rd
              messages:
              - text: Good job, you should be able to see your application logs in New Relic
                delay: 1000
          - actionId: finish_step
      else:
        do:
          - actionId: bot_message
            params:
              person: head-of-rd
              messages:
              - text: Umm, If you need any help, just let me know that you’re stuck. If that’s not the case - take your time and tell me once you're ready :)
                delay: 1000
